JamongSoda/IntoHistory

IntoHistory.xcodeproj/project.pbxproj

- json 파일이 xcode 내부에서 보이지 않음
- json 파일이 xcode 내부에서 보이지 않는 버그 수정
- 없음
- 없음
- 핫픽스입니다. 꼼꼼히 확인 후 리뷰 부탁드립니다.
- 없음
Close #17

[!HOTFIX] json 파일이 xcode에서 보이지 않는 버그 수정

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/Data/CourseData.swift
IntoHistory/Data/LoadingCourseJSON.swift
IntoHistory/Data/LoadingPersonJSON.swift
IntoHistory/Data/PersonData.swift

- 탐방경로와 인물정보를 불러오기 위한 기반 코드를 추가하기 위함.
- 탐방경로(CourseJSON), 인물정보(PersonJSON)에 대한 파일매니저를 추가하였습니다.
- 불필요 import CloudKit 입력된 내용 삭제
Close #16.

[Feat] Add Filemanager(CourseJSON, PersonJSON)

---

IntoHistory/Extension/AutoLayout+Extension.swift
IntoHistory/Extension/Color+Extension.swift

Auto Layout 및 Color에 대한 Extension을 추가합니다.
- Auto Layout 및 Color를 가독성있게 사용하기 위해 Extension 파일 제작
-Extension 파일 제작
- 없음
<br/>
- Auto Layout을 사용하게 해주신 규님께 감사를..
<br/>
Close #29

[Feature] Add Extension (Auto Layout & Color Extension)

---

IntoHistory.xcodeproj/project.pbxproj

이전에 develop에 marge한 autolayout 및 color Extension에서 누락한 project 파일을 업로드 합니다.
- 누락한 project 파일을 업로드
- 없음
- 없음
- 없음
- 죄송합니다.. 여러분..
- 없음
Close #33

[!HOTFIX] develop에서 Extension 파일이 보이지 않는 현상 해결

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/Assets.xcassets/AppIcon.appiconset/Contents.json
IntoHistory/NMapViewController.swift

- 네이버지도 출력
- 지도 사용 시 사용자 권한 요청
[앱에서 네이버지도 띄우기](https://velog.io/@dazzlynn/iOS-앱에서-네이버-지도-띄우기)
Close #39 .

[Feat] 네이버 지도 출력

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/NMapViewController.swift

- 코드 상에서 Filemanager를 찾지 못하는 문제로 인한 수정입니다.
- JSON 및 Filemanager를 내부 폴더로 옮겼습니다.
- 인식이 안 될거라고는 생각도 못했네요.. 죄송합니다
- HOTFIX 이후, rebase해주시면 감사하겠습니다.
Close #49 .

[!HOTFIX] 데이터 폴더 타입 변경 (외부 폴더 -> 내부 폴더)

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/Data/CourseData.swift
IntoHistory/Literal/ImageLiteral.swift

- 지도에 사용할 마커(핀)을 사용하기 위함
- 이미지 리터럴 추가 및 핀 선택 함수 추가
Close #51.

[Resource] Add ImageLiteral & selectedPinTypes

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/Extension/Color+Extension.swift
IntoHistory/Info.plist
IntoHistory/Screens/ARView/ARViewController.swift
IntoHistory/Screens/ARView/SupportViews/ARView.storyboard
IntoHistory/Screens/ARView/SupportViews/TempButtonViewController.swift

- ARView를 생성했습니다.
- TempButtonViewController : 임시로 화면 전환을 넣기 위한 뷰컨트롤러입니다. 전혀 신경쓰지 않아도 되고, 추후 mainview랑 연결 후 삭제할 예정입니다.
- ARView : 스토리보드로 Scene을 추가해주었습니다. (코드베이스로도 가능할텐데, 이해가 어려워 일단 스토리보드로 구현)
- ARViewController : ARView 스토리보드와 연결된 뷰 컨트롤러
|AR화면 동작 gif|
|---|
|![AR](https://user-images.githubusercontent.com/96969693/184379367-01dd0056-9656-42a5-aaca-6c79ed74b7ee.gif)|
- 메인이 머지되면, 화면 연결을 하겠습니다.
- TempButtonViewController는 삭제예정입니다.
- 아직 AR에서 공이 하얀색으로 뜨는데, 추후 이미지 추가 예정입니다!
- 마지막에 공을 클릭하면 dismiss되어 modal이 내려가는 상황입니다. 현재 AR을 모달로 띄운상태인데, 이렇게 되게 되면 ```맨 마지막 루트를 방문했을때 AR로 가는 버튼 클릭 -> 모달로 AR등장 -> 객체 클릭시 화면 전환``` 이렇게 되는데, 보통 모달에서 화면전환이 이루어지기도 하나요??? 
https://www.applaudostudios.com/blog/posts/augmented-reality-planetarium-using-arkit
Close #38

[Feature] AR뷰 추가

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/NMapViewController.swift

- 집 나갔던 NMapViewController.swift 파일 복구
- NMapViewController.swift 파일이 `develop` 브랜치에서 사라진 현상이 발생하여 복구했습니다.
- NMapViewController.swift 파일 복구
- 없음
- 없음
- 핫픽스입니다. 신속, 정확한 리뷰 부탁드려요.
- 없음
Close #75

[!HOTFIX] 집 나간 NMapViewController.swift 파일 복구

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/NMapViewController.swift

- 집 나갔던 NMapViewController.swift 파일 복구
- NMapViewController.swift 파일이 `develop` 브랜치에서 사라진 현상이 발생하여 복구했습니다.
- NMapViewController.swift 파일 복구
- 없음
- 없음
- 핫픽스입니다. 신속, 정확한 리뷰 부탁드려요.
- 이미 한번 리뷰된 코드이지만 다시 한 번 신속 정확하게 리뷰 부탁드립니다.
- 없음
Close #75

[!HOTFIX] 집 나간 NMapViewController.swift 파일 복구 (Merge bugfix to develop)

---

IntoHistory/Screens/ARView/SupportViews/TempButtonViewController.swift

- 화면 전환 방식을 바꾸었습니다.
- 원래 AR화면이 모달창으로 띄워졌는데, 이 방식을 navigatiion으로 전환되게 바꾸었습니다.
|변경 전 (모달)|변경 후 (네비게이션)|
|---|---|
|![AR](https://user-images.githubusercontent.com/96969693/184496120-08c1c08c-87ed-4b5c-ae14-c8fa42c0763f.gif)|![navigation](https://user-images.githubusercontent.com/96969693/184496170-16c285e2-75dd-4127-a85f-71f81801e9be.gif)|
none
Close #56

[Feature] AR화면 전환 방식 변경

---

IntoHistory.xcodeproj/project.pbxproj

- 파일매니저에서 json 파일을 정상적으로 불러오지 못하는 버그 발생
- pbx에서 bundle resource 부분에 json 파일들이 빠진 것으로 추정되어 해당 부분을 수정
- 파일 매니저에서 json 파일을 정상적으로 불러오지 못하는 버그 수정
- 없음
- 없음
- 핫픽스입니다. 간단한 수정이지만 pbx 수정인 만큼 주의해서 봐주시면 감사하겠습니다.
- `bugfix` 브랜치에서 `develop` 브랜치로 Merge 입니다. 한 번 확인 받은 코드이지만 다시 한번 리뷰 부탁드려요~
- 없음
Close #79

[!HOTFIX] 파일 매니저에서 json 파일을 정상적으로 불러오지 못하는 버그 수정 (Merge bugfix to develop)

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/DetailCourseView/DetailCourseCell.swift
IntoHistory/DetailCourseView/DetailCourseHeader.swift
IntoHistory/DetailCourseView/DetailCourseViewController.swift

- 상세내용 뷰 레이아웃 추가
- 데이터 불러오기 완료
- 삽질을 오래 했더니 코드도 길어졌네요.. ㅠㅠ
Close #83 .

[Feature] Add DetailCourseView(상세내용 뷰 레이아웃)

---

IntoHistory/HeroDetailViewController.swift
IntoHistory/HeroListViewController.swift
IntoHistory/NMapViewController.swift

- 영웅 목록에서 영웅을 클릭했을 때 영웅의 상세정보를 보여주기 위해 모달을 띄우는 기능이 필요하여 추가
- 영웅 상세 모달에서 닫기 버튼을 눌렀을 때 모달을 닫는 기능이 필요하여 추가
- 영웅 목록에서 영웅을 클릭했을 때 모달을 띄워주는 기능 추가
- 영웅 상세 모달에서 닫기 버튼을 눌렀을 때 모달을 닫는 기능 추가 b1ee5f2
- 팝업을 띄우는 기능을 구현했습니다. 꽤나 짧고 간결한 코드이니 꼼꼼한 리뷰 부탁드립니다.
- 닫기 버튼으로 팝업을 닫는 기능이 추가되었습니다. 추가 리뷰 부탁드립니다.
- `heropopup` branch에서 `develop` branch로 Merge입니다. 한번 보셨더라도 다시 한번 꼼꼼한 리뷰 부탁드립니다.
- [Soda Blog - [iOS/Swift] 모서리가 둥근, 그림자가 적용된 팝업 뷰 구현하기](https://jellysong.tistory.com/82)
- Close #95 
- Close #98

[Feature] 영웅을 클릭했을 때 모달 띄우고, 닫기 버튼 클릭으로 모달 닫는 기능 추가 (Merge heropopup to develop)

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/CourseListView/CourseListCell.swift
IntoHistory/CourseListView/CourseListViewController.swift
IntoHistory/DetailCourseView/DetailCourseCell.swift
IntoHistory/DetailCourseView/DetailCourseViewController.swift
IntoHistory/Info.plist
IntoHistory/NMapViewController.swift

- 마커(핀) 터치 시 장소 및 주소 설명하는 플로팅 뷰 추가
- 마커 선택 시 '선택한 것'과 '선택하지 않은' 마커(핀)을 전환하는 기능 추가
- ㅠㅠ
Close #91.

[Feature] Add FloatingView of nmap & Changing marker(pin)

---

IntoHistory/CourseListView/CourseListCell.swift
IntoHistory/CourseListView/CourseListViewController.swift
IntoHistory/DetailCourseView/DetailCourseCell.swift
IntoHistory/DetailCourseView/DetailCourseViewController.swift
IntoHistory/Info.plist
IntoHistory/NMapViewController.swift

- 마커(핀) 터치 시 장소 및 주소 설명하는 플로팅 뷰 추가
- 마커 선택 시 '선택한 것'과 '선택하지 않은' 마커(핀)을 전환하는 기능 추가
- ㅠㅠ
Close #91.

[!Feature] Add FloatingView of nmap & Changing marker(pin)

---

IntoHistory.xcodeproj/project.pbxproj
IntoHistory/ARView/ARView.storyboard
IntoHistory/ARView/ARViewController.swift
IntoHistory/ARView/TempButtonViewController.swift

- 갑작스러운 프로젝트 사망으로 develop에서 다시 브랜치를 파서 코드르 붙여넣었습니다.
- ARView 코드입니다.
컨플릭트 나름 잘 해결해서 머지했다고 생각했는데 아니었네요 ^___^ 앞으론 주의할게여,,, 
Close #126

[!Feature] 프로젝트 사망으로 arview 코드 복사해서 다시 작성 (Merge arview_new to develop)

---

IntoHistory/ChangeViewController.swift
IntoHistory/DetailCourseView/DetailCourseViewController.swift

- DetailCourseView SafeArea의 배경색이 들어가지 않은 문제
- DetailCourseView SafeArea의 배경색이 들어가지 않은 문제 해결
Close #131 .

[Fix] DetailCourseView SafeArea 색상 추가(흰색)

---

IntoHistory/AppDelegate.swift
IntoHistory/LocationService.swift

- notificatoin 문구에 해당 지역명 추가
- 해당지역 핀 updatePinIsVisite 업데이트
- 없음
Close #112

[Feature] notificatoin에 해당 지역명 추가 및 updatePinIsVisite

---

IntoHistory/AppDelegate.swift
IntoHistory/Info.plist

- 다크모드 해제
- 세료모드로 고정 -> target에서 적용할 수있는데 적용되지 않아서 코드베이스로 적용했습니다. (적용이안되는 경우가 있다고 인터넷에서 그랬음!)
- 카메라 접근허용 info.plist 추가
으랏차차 별거 없는 코드입니다. 
plist수정이 대부분이지만 꼼꼼하게 확인해주시고 리뷰 해주세용!
해당 pr은 바로 develop으로 머지됩니다. 한번만 리뷰해주시면 됩니다.!
Close #154

[Chore] 다크모드 해제, 세로로 고정, 카메라 접근허용 plist 수정 (Merge "this branch" to develop)

---

IntoHistory/ARView/ARViewController.swift
IntoHistory/ARView/HeroCollectedViewController.swift
IntoHistory/AppDelegate.swift
IntoHistory/DetailCourseView/DetailCourseViewController.swift
IntoHistory/Extension/Color+Extension.swift
IntoHistory/HeroListView/HeroListViewController.swift
IntoHistory/NMapViewController.swift

- ARView와 관련된 데이터 바인딩
- 맵 메모리 누수 해결
- 영웅 목록 이미 수집된 상태로 나오는 문제 해결
- 아직 만나지 못한 영웅 이름 변경
- 아직 완료하지 못한 코스의 버튼 비활성화
- ARView와 관련된 데이터 바인딩
- 맵 메모리 누수 해결
- 영웅 목록 이미 수집된 상태로 나오는 문제 해결
- 아직 만나지 못한 영웅 이름 변경
- 아직 완료하지 못한 코스의 버튼 비활성화
- 없음
- 없음
- PR을 나눴어야 했는데, 급하게 작업하느라 못나눴네요. 죄송합니다 ㅠㅠ
- 중요한 부분이 많으니 꼼꼼한 리뷰 부탁드립니다.
- `databinding` branch에서 `develop` branch로의 merge입니다. 이미 한번 보신 코드일 수 있지만, 다시 한번 꼼꼼한 리뷰 부탁드려요~
- 없음
Close #61

[Feature] 데이터 바인딩, 맵 메모리 누수 해결, 영웅 목록 수정, 코스 버튼 수정 및 자잘한 수정 (Merge databinding to develop)
